#!/usr/bin/env bash

echo "Sending report to SonarQube server..." >&2

sonar-scanner \
  -Dsonar.projectKey=sonarqube-sail \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.login=sqp_1f39e9043a42643eeee838cd6e2e4f1bf9b74229

echo "Opening SonarQube Gui..." >&2

sensible-browser http://localhost:9000/dashboard?id=sonarqube-sail